# Generated by Django 5.0.2 on 2025-05-20 22:58

import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=users.models.get_default_expiry),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
