# Generated by Django 5.0.2 on 2025-05-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_requested_agent'),
        ('users', '0002_alter_verificationtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='users.agency'),
        ),
    ]
