# Generated by Django 5.0.2 on 2025-05-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_assigned_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Whether the agent has accepted this lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
