# Generated by Django 5.0.2 on 2025-05-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_accepted_at_lead_is_accepted_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
