# Generated by Django 5.0.2 on 2025-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address of the property', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='suburb',
            field=models.CharField(blank=True, help_text='Suburb or town of the property', max_length=100, null=True),
        ),
    ]
