# Generated by Django 5.0.2 on 2025-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_street_address_lead_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='preferred_agent',
            field=models.CharField(blank=True, help_text="Spotter's preferred agent (free text)", max_length=255),
        ),
    ]
