# Generated by Django 5.0.2 on 2025-06-21 10:27

import django.db.models.deletion
import listings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('suburb', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('gauteng', 'Gauteng'), ('western_cape', 'Western Cape'), ('eastern_cape', 'Eastern Cape'), ('kwazulu_natal', 'KwaZulu-Natal'), ('free_state', 'Free State'), ('mpumalanga', 'Mpumalanga'), ('limpopo', 'Limpopo'), ('north_west', 'North West'), ('northern_cape', 'Northern Cape')], max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('cottage', 'Cottage'), ('farm', 'Farm'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20)),
                ('custom_property_type', models.CharField(blank=True, help_text='Custom property type if not in the list', max_length=100)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_pet_friendly', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.property_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.propertylisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
