# Generated by Django 5.0.2 on 2025-06-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Optional: Assign to a specific agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
