# Generated by Django 5.0.2 on 2025-06-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_propertylisting_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='slug',
        ),
    ]
