# Generated by Django 5.0.2 on 2025-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_url',
            field=models.URLField(blank=True, help_text='URL where the property is listed (e.g., Property24, PrivateProperty)', max_length=500, null=True),
        ),
    ]
