# Generated by Django 5.0.2 on 2025-05-20 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='commission',
            name='spotter',
            field=models.ForeignKey(limit_choices_to={'role': 'Spotter'}, on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
